name: biobb_wf_structure_checking
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_model==4.1.0
  - biobb_chemistry==4.1.0
  - biobb_amber==4.1.0
  - modeller
  - jupyter_client==7.3.2
  - nb_conda_kernels
  #Â - importlib_metadata
  - traitlets==5.9.0
  - jupyter_contrib_nbextensions
  - plotly
  - nglview
  - conda
