name: biobb_wf_structure_checking
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - biobb_io==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_model==5.2.0
  - biobb_chemistry==5.2.0
  - biobb_amber==5.2.0
  - modeller
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
